---
- name: Create
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./group_vars/vars.yml
  roles:
    - node_create

- name: Config
  hosts: linodes
  vars_files:
    - ./group_vars/vars.yml
  user: root
  gather_facts: true
  roles:
    - node_config

