---
- name: Create Linode instance
  block:
    - name: Provision node
      linode.cloud.instance:
        api_token: "{{ linode_token }}"
        label: "{{ linode_label }}"
        type: "{{ linode_type }}"
        region: "{{ linode_region }}"
        image: "{{ linode_image }}"
        root_pass: "{{ password }}"
        authorized_keys:
          - "{{ ssh_key }}"
        wait: true
        wait_timeout: 300
        state: present
      register: instance_result

    - name: Display host information
      debug:
        msg: 
          "CREATED {{ instance_result.instance.label }} => {{ instance_result.instance.ipv4[0] }}"

    - name: Add the new host to dynamic inventory
      add_host:
        hostname: "{{ instance_result.instance.ipv4[0] }}"
        groupname: linodes

    - name: Wait for SSH to come up
      local_action:
        module: wait_for
        delay: 60
        host: "{{ instance_result.instance.ipv4[0] }}"
        port: 22
        timeout: 300
